[workspace]
resolver = "2"
members = [ "crates/calf", "crates/oracles"]

[workspace.dependencies]
category_theory = { path = "/Users/mwas/RustroverProjects/CategoryTheory" }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
